// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotWE8rZ_mc2clMsqKXiwsoWvrceqSAsU',
    appId: '1:509650098162:web:bd1cebb0aa626c8f547d6b',
    messagingSenderId: '509650098162',
    projectId: 'ugma-aventon',
    authDomain: 'ugma-aventon.firebaseapp.com',
    storageBucket: 'ugma-aventon.firebasestorage.app',
    measurementId: 'G-T6L3E01C5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0wOmb22HJ1vs5WavfdJtFgNUJF-MepE',
    appId: '1:509650098162:android:233a4ad87f2a2660547d6b',
    messagingSenderId: '509650098162',
    projectId: 'ugma-aventon',
    storageBucket: 'ugma-aventon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuESgNvKaqv6JyeA14IQA2g4v_4lNcuSQ',
    appId: '1:509650098162:ios:4d65dc9812039620547d6b',
    messagingSenderId: '509650098162',
    projectId: 'ugma-aventon',
    storageBucket: 'ugma-aventon.firebasestorage.app',
    iosBundleId: 'com.example.ugmaventon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuESgNvKaqv6JyeA14IQA2g4v_4lNcuSQ',
    appId: '1:509650098162:ios:4d65dc9812039620547d6b',
    messagingSenderId: '509650098162',
    projectId: 'ugma-aventon',
    storageBucket: 'ugma-aventon.firebasestorage.app',
    iosBundleId: 'com.example.ugmaventon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBotWE8rZ_mc2clMsqKXiwsoWvrceqSAsU',
    appId: '1:509650098162:web:528114ded3ae98bf547d6b',
    messagingSenderId: '509650098162',
    projectId: 'ugma-aventon',
    authDomain: 'ugma-aventon.firebaseapp.com',
    storageBucket: 'ugma-aventon.firebasestorage.app',
    measurementId: 'G-FKCWDDZY3V',
  );
}
